name: Run PowerShell Script

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter the username"
        required: true
        type: string
      useremail:
        description: "Enter the user email"
        required: true
        type: string

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display User Inputs
        shell: pwsh
        run: |
          Write-Host "The entered username is: ${{ github.event.inputs.username }}"
          Write-Host "The entered user email is: ${{ github.event.inputs.useremail }}"
